import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SupabaseListener from "./components/supabase-listener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body suppressHydrationWarning className="flex flex-col min-h-screen">
        <SupabaseListener />
        <main className="flex-1 container max-w-screen-sm mx-auto px-1 py-5">
          {children}
        </main>
        <footer className="tex-center text-sm">
          Copyright &copy; All right reserved
        </footer>
      </body>
    </html>
  );
}
